### ISSUE TITLE
The Document has been started but it's incomplete!

### ISSUE THREAD

**Issue by setco-website** [praveenscience/Apache-Local-Community-Git-GitHub#1]
Hey I am a great writer, you can check my profile for all my contributions.

I feel that this project can be made better by adding more details on the main ReadMe file.

I feel I can contribute to this project and make it better. Would you like to please assign me.

**Comment by praveenscience** [comment]
Yea, please go ahead, I am really busy so I couldn't do anything further, so it will be nice if you take it up! 😊

**Comment by setco-website** [comment]
Yes, I'll start working on it.

**Comment by ronisarkarexe** [comment]
I will start
